# Generated by Django 3.2.3 on 2021-05-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.answers')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.questions')),
            ],
        ),
    ]
